#!/usr/bin/env python
# coding: utf-8

# In[4]:


import pandas as pd
import numpy as np
import sklearn as sk


# In[5]:


import pandas as pd
train = pd.read_csv(r'C:\Users\kritika1\Desktop\OV_9 Classification\OV_9_Data.csv')
print (train)


# In[6]:


train.info()


# In[7]:


train.describe(include = 'all')


# # Number of Words

# In[8]:


train['word_count'] = train['Justifications'].apply(lambda x: len(str(x).split(" ")))
train[['Justifications','word_count']].head()


# # Number of characters

# In[9]:


train['char_count'] = train['Justifications'].str.len() ## this also includes spaces
train[['Justifications','char_count']].head()


# # Average Word Length

# In[10]:


def avg_word(sentence):
  words = str(sentence).split()
  return (sum(len(word) for word in words)/len(words))

train['avg_word'] = train['Justifications'].apply(lambda x: avg_word(x))
train[['Justifications','avg_word']].head()


# # Number of stopwords

# In[11]:


from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS


# In[12]:


from sklearn.feature_extraction import stop_words
stop =stop_words.ENGLISH_STOP_WORDS
print(stop)


# In[13]:


train['stopwords'] = train['Justifications'].apply(lambda x: len([x for x in str(x).split() if x in stop]))
train[['Justifications','stopwords']].head()

#Number of special characters
# # Lower case

# In[14]:


train['Justifications'] = train['Justifications'].apply(lambda x: " ".join(x.lower() for x in str(x).split()))
train['Justifications'].head()


# # Removing Punctuation

# In[15]:


train['Justifications'] = train['Justifications'].str.replace('[^\w\s]','')
train['Justifications'].head()


# # Removal of Stop Words

# In[16]:



train['Justifications'] = train['Justifications'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
train['Justifications'].head()


# # Common word removal

# In[17]:


freq = pd.Series(' '.join(train['Justifications']).split()).value_counts()[:20]
print(freq)


# In[18]:


freq = list(freq.index)
train['Justifications'] = train['Justifications'].apply(lambda x: " ".join(x for x in str(x).split() if x not in freq))
train['Justifications'].head()


# # Rare words removal

# In[19]:


freq = pd.Series(' '.join(train['Justifications']).split()).value_counts()[-50:]
print(freq)


# In[20]:


freq = list(freq.index)
train['Justifications'] = train['Justifications'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
train['Justifications'].head()


# In[21]:


# Removing Short Words

train['Justifications'] = train['Justifications'].apply(lambda x: ' '.join([w for w in str(x).split() if len(w)>3]))
train['Justifications'].head()


# # Tokenization

# In[22]:


# Tokenization
#Tokens are individual terms or words, and tokenization is the process of splitting a string of text into tokens.

tokenized_Justifications = train['Justifications'].apply(lambda x: str(x).split())
tokenized_Justifications.head()


# # Stemming

# In[23]:


from nltk.stem.porter import *
stemmer = PorterStemmer()

tokenized_Justifications = tokenized_Justifications.apply(lambda x: [stemmer.stem(i) for i in x]) # stemming
tokenized_Justifications.head()


# In[24]:


# jonning the tokens back 

for i in range(len(tokenized_Justifications)):
    tokenized_Justifications[i] = ' '.join(tokenized_Justifications[i])

train['tidy_Justifications'] = tokenized_Justifications

train.head()
train.shape


# In[25]:


df=train
df.head(2)


# In[27]:


col = ['OVR_Reasons', 'tidy_Justifications']
df = df[col]
df.columns

# Plot Graph
# In[28]:


from io import StringIO

df = df[pd.notnull(df['tidy_Justifications'])]
df.columns = ['OVR_Reasons', 'tidy_Justifications']

df['category_id'] = df['OVR_Reasons'].factorize()[0]

category_id_df = df[['OVR_Reasons', 'category_id']].drop_duplicates().sort_values('category_id')
category_to_id = dict(category_id_df.values)
id_to_category = dict(category_id_df[['category_id', 'OVR_Reasons']].values)
df.head()


# In[30]:


import matplotlib.pyplot as plt
fig = plt.figure(figsize=(8,6))
df.groupby('OVR_Reasons').tidy_Justifications.count().plot.bar(ylim=0)
plt.show()


# # Features Extraction  into features

# In[32]:


from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
features = tfidf.fit_transform(df.tidy_Justifications).toarray()
labels = df.category_id
features.shape


# In[34]:


from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
# TF-IDF feature matrix
tfidf = tfidf_vectorizer.fit_transform(df['tidy_Justifications'])
tfidf.shape


# # features_chi2

# In[35]:


from sklearn.feature_selection import chi2
import numpy as np
N = 2
for Product, category_id in sorted(category_to_id.items()):
  features_chi2 = chi2(features, labels == category_id)
  indices = np.argsort(features_chi2[0])
  feature_names = np.array(tfidf.get_feature_names())[indices]
  unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
  bigrams = [v for v in feature_names if len(v.split(' ')) == 2]
  print("# '{}':".format(Product))
  print("  . Most correlated unigrams:\n. {}".format('\n. '.join(unigrams[-N:])))
  print("  . Most correlated bigrams:\n. {}".format('\n. '.join(bigrams[-N:])))


# # Build Model 

# In[ ]:


from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

xtrain, xtest, ytrain, ytest = train_test_split(train['Justifications'], df['OVR_Reasons'], random_state = 0)


# In[ ]:


from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(xtrain, ytrain)
y_pred = clf.predict(x_test)

train_score = clf.score(xtrain, ytrain)
test_score = clf.score(xtest, ytest)

train_score, test_score


# In[ ]:


# Init the Gaussian Classifier
model = MultinomialNB()

# Train the model 
model.fit(xtrain, ytrain)

# Predict Output 
pred = model.predict(xtest)

# Plot Confusion Matrix
mat = confusion_matrix(pred, ytest)
names = np.unique(pred)
sns.heatmap(mat, square=True, annot=True, fmt='d', cbar=False,
            xticklabels=names, yticklabels=names)
plt.xlabel('Truth')
plt.ylabel('Predicted')


# In[ ]:


from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(df['tidy_Justifications'], df['OVR_Reasons'], random_state = 0)

count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

clf = MultinomialNB().fit(X_train_tfidf, y_train)


# In[ ]:


X_train, X_test, y_train, y_test = train_test_split(df['Justifications'], df['OVR_Reasons'], random_state = 0)


# In[ ]:


X_test.shape


# In[ ]:


count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
print(X_train_counts)


# In[ ]:


tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
print(X_train_tfidf)


# In[ ]:


print(X_train_tfidf)

